### ISSUE TITLE
Default Script Fails when Run with Testing/Training Data

### ISSUE THREAD

**Issue by cai-michael** [mnielLab/netTCR#2]
When running the default test script `python scripts/netTCR.py -infile test_data/data.txt -outfile NetTCR_predictions.txt` using either Python 2.7.17 or Python 3.6.9 I get the following output:

`Traceback (most recent call last):
  File "scripts/netTCR.py", line 170, in <module>
    best_params = np.load(param_dir + "params.t." + str(t) +  ".v." + str(v) + ".s." + str(s) + ".npz")['arr_0']
  File "/home/local/ASUAD/mrcai/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/local/ASUAD/mrcai/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
`

As a workaround at the moment you can downgrade numpy to 1.16.1 to be able to run the script successfully.

I think the default value in numpy has changed and allow_pickle needs to be directly assigned as True.

**Comment by cai-michael** [comment]
https://github.com/mnielLab/netTCR/blob/070fda121360880de549176200db48da75568084/parameters/iedb_mira_pos_uniq.txt#L3092

https://github.com/mnielLab/netTCR/blob/070fda121360880de549176200db48da75568084/parameters/iedb_mira_pos_uniq.txt#L3012

https://github.com/mnielLab/netTCR/blob/070fda121360880de549176200db48da75568084/parameters/iedb_mira_pos_uniq.txt#L1594

There's also some training data that seems to have numbers that don't belong when I try to run the data on the training set even.
